version: "3.8"
services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  spring-boot:
    build:
      context: ./spring-boot-app
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
